# The contents of this file are parsed and made available as
# via `site.*`. So for example, {{ site.title }} can be used
# in a template to get the contents of the `title` key.
title: MisFacturas.space
subtitle: Nuestro sistema te ayuda a guardar y mantener ordenadas y seguras tus facturas electrónicas, puedes buscarlas, obtener estadísticas.

google_analytics_tracking_id: UA-62298489-1
# Insert your disqus shortname
#disqus:
#    shortname:
